import { Gauge, Sun, Home } from "lucide-react";

const specializations = [
  {
    icon: Gauge,
    title: "SMART METERS",
    description:
      "Smart consumption meters can be installed for both residential and commercial areas. These devices allow the user to manage and monitor, totally or partially, the energy consumption and control remotely the operation of the premises' electrical appliances via wi-fi. The device recognizes the energy footprint of each: the electrical device separately, resulting in the control of the energy consumption of the required area.",
  },
  {
    icon: Sun,
    title: "SELF PRODUCTION",
    description:
      "Self Consumption PV Systems are those which can be installed in the property of a commercial consumer (factory, block of offices, supermarkets, etc) of installed capacity between 10 and 500 kwp. Such a system has the potential to cover the electricity needs of the property in match with the consumption. PV production not in match with electricity consumption will be injected into the grid with no benefit for the property owner.",
  },
  {
    icon: Home,
    title: "NET METERING",
    description:
      "We have the energy to upgrade your living standard. According to the net metering scheme, every household gets the opportunity to install up to 10 KW PV system at the residence. The savings generated by such a system has the potential to pay the initial investment in less than 5 years, drastically reducing the running costs of the property.",
  },
];

const SpecializationSection = () => {
  return (
    <section id="services" className="bg-secondary py-16">
      <div className="container-section py-0">
        <h2 className="section-heading text-center">Our Specialization</h2>
        <p className="text-center text-muted-foreground max-w-4xl mx-auto mb-12">
          We will provide you with complete project management and consultancy services, including application submission, system design and sizing and subsidy arrangements to final completion and handover. Having installed more than 300 photo-voltaic systems these past years, we are experienced in the procedure and able to overcome any obstacles or engineering challenges which may arise.
        </p>
        <p className="text-center text-muted-foreground max-w-4xl mx-auto mb-12">
          Fingren energy created the net-metering project that allows consumers and local authorities to generate up to 3kW of electricity using solar panel technology delivering the generated electricity to the local distribution facilities in a more cost effective approach.
        </p>

        <div className="grid md:grid-cols-3 gap-8">
          {specializations.map((item, index) => (
            <div
              key={item.title}
              className="bg-background p-6 rounded-lg shadow-sm hover:shadow-md transition-shadow animate-fade-in"
              style={{ animationDelay: `${index * 0.1}s` }}
            >
              <div className="flex items-center gap-3 mb-4">
                <div className="p-2 bg-primary/10 rounded-lg">
                  <item.icon className="w-6 h-6 text-primary" />
                </div>
                <h3 className="font-heading font-semibold text-foreground">{item.title}</h3>
              </div>
              <p className="text-sm text-muted-foreground leading-relaxed">{item.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default SpecializationSection;
